export enum MethodKeys {
  Undefined = 'undefined',
  Get = 'get',
  Post = 'post',
  Put = 'put',
  Patch = 'patch',
  Delete = 'delete',
  Copy = 'copy',
  Head = 'head',
  Options = 'options',
  Purge = 'purge',
  Lock = 'lock',
  Unlock = 'unlock',
  Propfind = 'propfind',
}
