declare type Document = any;
export declare function Module(mountPoint?: string, document?: Document): ClassDecorator;
export declare function Get(path?: string, document?: Document): MethodDecorator;
export declare function Post(path?: string, document?: Document): MethodDecorator;
export declare function Put(path?: string, document?: Document): MethodDecorator;
export declare function Patch(path?: string, document?: Document): MethodDecorator;
export declare function Delete(path?: string, document?: Document): MethodDecorator;
export declare function Copy(path?: string, document?: Document): MethodDecorator;
export declare function Head(path?: string, document?: Document): MethodDecorator;
export declare function Options(path?: string, document?: Document): MethodDecorator;
export declare function Purge(path?: string, document?: Document): MethodDecorator;
export declare function Lock(path?: string, document?: Document): MethodDecorator;
export declare function Unlock(path?: string, document?: Document): MethodDecorator;
export declare function Propfind(path?: string, document?: Document): MethodDecorator;
export declare function Validator(document?: Document): ClassDecorator;
export declare function Service(document?: Document): ClassDecorator;
export declare function Controller(prefix: string, document?: Document): ClassDecorator;
export declare function ScheduledController(every: number, document?: Document): ClassDecorator;
export declare function RealtimeController(path: string, document?: Document): ClassDecorator;
export declare function ControllerMiddleware(middlewares: Array<Function>, document?: Document): ClassDecorator;
export declare function Middleware(document?: Document): ClassDecorator;
export declare function MethodMiddleware(middlewares: Array<Function>, document?: Document): MethodDecorator;
export declare function COR(): ClassDecorator;
export {};
